### Elasticity
* All the output are from program only,
the clamp have been commented in program for now

In [1]:
import resources #Must be 1st line
import pandas as pd
from blcalc.material import Material

In [2]:
datas = {'N60': [], 'clay': [], 'sand': []}
for N60 in range(0, 76, 5):
    datas['N60'].append(N60)
    mat1=Material({'depth':0,'n60':N60, 'GI':'C'})
    datas['clay'].append(mat1.get()['e'])
    mat2=Material({'depth':0,'n60':N60, 'GI':'S'})
    datas['sand'].append(mat2.get()['e'])
pd.DataFrame(datas)

    N60       clay   sand
0     0        0.0      0
1     5    13750.0   5000
2    10    60000.0  10000
3    15    90000.0  15000
4    20   120000.0  20000
5    25   150000.0  25000
6    30   180000.0  30000
7    35   490000.0  35000
8    40   560000.0  40000
9    45   630000.0  45000
10   50   700000.0  50000
11   55   770000.0  55000
12   60   840000.0  60000
13   65   910000.0  65000
14   70   980000.0  70000
15   75  1050000.0  75000

Need checks before start clampoing